### ISSUE TITLE
Unable to find "snowpack-react-tailwind" in the npm registry.

### ISSUE THREAD

**Issue by markfirmware** [mrkldshv/snowpack-react-tailwind#2]
npx create-snowpack-app --template snowpack-react-tailwind abc
    npx: installed 29 in 11.045s

    [ERROR] Unable to find "snowpack-react-tailwind" in the npm registry.
    [ERROR] Cannot continue safely. Exiting...

**Comment by mrkldshv** [comment]
Hey! 
Sorry for the delay. I will look into this in the next days.

**Comment by markfirmware** [comment]
Thanks!

**Comment by mrkldshv** [comment]
I have just republished it on npm. It should be fine now.

**Comment by markfirmware** [comment]
Thank you! No problems.
